import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  /*{
    path: 'configuraciones',
    title: 'Configuraciones',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: 'bitacora',
        title: 'Bitacora',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'usuarios',
        title: 'Usuarios',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      }
    ]
  },
  {
    path: 'contabilidad',
    title: 'Contabilidad',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: 'dadsadsadsadsadsad',
        title: 'dsadsadsadsad',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      }
    ]
  }*/
  {
    path: 'individual',
    title: 'Formularios Empresa Individual',
    icon: 'mdi mdi-tie',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: 'solicitud-individual',
        title: 'Solicitud',
        icon: 'mdi mdi-file-document',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'perfil-individual',
        title: 'Perfil',
        icon: 'mdi mdi-account-card-details',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'feic-individual',
        title: 'FEIC',
        icon: 'mdi mdi-cash',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'ive-productos-individual',
        title: 'IVE Productos',
        icon: 'mdi mdi-cash-multiple',
        class: 'IVE Productos',
        extralink: false,
        submenu: [],
      },
      {
        path: 'cpe-individual',
        title: 'CPE',
        icon: 'mdi mdi-pencil-box-outline',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'pep-individual',
        title: 'PEP',
        icon: 'mdi mdi-square-inc-cash',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'autorizacion-consulta-individual',
        title: 'Autorizaciones para consultas',
        icon: 'mdi mdi-pen',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'carta-banco-internacional-individual',
        title: 'Carta para el banco internacional',
        icon: 'mdi mdi-bank',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'estado-patrimonial-individual',
        title: 'Estado patrimonial',
        icon: 'mdi mdi-home',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'flujo-fondos-individual',
        title: 'Flujo de fondos',
        icon: 'mdi mdi-coins',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'endeudamiento-bancario-individual',
        title: 'Endeudamiento bancario',
        icon: 'mdi mdi-coin',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'formato-integraciones-individual',
        title: 'Formato para integraciones',
        icon: 'mdi mdi-file-document-box',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'registro-deudores-individual',
        title: 'Registro de deudores',
        icon: 'mdi mdi-account-switch',
        class: '',
        extralink: false,
        submenu: [],
      }
    ]
  },

  {
    path: 'empresa',
    title: 'Formularios Empresa Jurídica',
    icon: 'mdi mdi-briefcase',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: 'solicitud-empresa',
        title: 'Solicitud',
        icon: 'mdi mdi-file-document',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'perfil-empresa',
        title: 'Perfil',
        icon: 'mdi mdi-account-card-details',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'IVE 02',
        icon: 'mdi mdi-cash-multiple',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'IVE Productos',
        icon: 'mdi mdi-cash-multiple',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'FEIC',
        icon: 'mdi mdi-cash',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'CPE',
        icon: 'mdi mdi-file-document',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'PEP',
        icon: 'mdi mdi-square-inc-cash',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'Autorizaciones para consultas',
        icon: 'mdi mdi-pen',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'Carta para el Banco Internacional',
        icon: 'mdi mdi-bank',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'Estado patrimonial',
        icon: 'mdi mdi-home',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'Flujo de fondos',
        icon: 'mdi mdi-coins',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'Endeudamiento bancario',
        icon: 'mdi mdi-bank',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'Formatos para integraciones',
        icon: 'mdi mdi-file-document-box',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'Registro de deudores',
        icon: 'mdi mdi-account-switch',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: 'dashboard',
        title: 'Punto de Acta',
        icon: 'mdi mdi-file-document',
        class: '',
        extralink: false,
        submenu: [],
      }
    ]
  },
];

/* 
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'Administración',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Tablero',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Usuarios',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Permisos',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Configuraciones',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Catálogos',
        icon: 'mdi mdi-arrange-bring-to-front',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Nuevos Servicios',
        icon: 'mdi mdi-image-filter-vintage',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '/email',
        title: 'Enviar Correos',
        icon: 'mdi mdi-email',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Clientes',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Seguimiento Clientes',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Tipos Clientes',
        icon: 'mdi mdi-tablet',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Requisitos',
        icon: 'mdi mdi-backburger',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Neg. Pronto Pago',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Proveedores',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Compras',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Proveedores',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reportes',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Préstamos',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Cuotas niveladas',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Identidad y estructura',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Intereses',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Capital vencidos',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Requerimientos de Prestamos',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Interés',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Periodicidad',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reportes',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Divisas',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Activos fijos',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Activos',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reportes',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Neg. Tradiciones',
    icon: 'mdi mdi-widgets',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '',
    title: 'Área Cumplimiento',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Listas Inter.',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reportes',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Alertas',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Neg. y Cobros',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Comisiones',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Cartera Vencida',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Cobros',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Facturación y Devoluciones',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Contabilidad',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Partidas contables',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Cheques',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Divisas',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Conciliaciones',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reportes',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Bancos',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Anulaciones',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Emisiones',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Negociaciones',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Diferencial cambiario',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Operaciones bancarias',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Modulo de facturación',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Reporte de facturas emitidas',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reporte de facturas cobradas',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Bonos, mora y complemento',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Penalizaciones',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reporte consolidado',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Legal y Comité',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Certificacion',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Casos especiales',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Flujo de fondos',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reportes',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'RRHH',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Planillas',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Pólizas',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Liquidaciones',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Boletas de pago',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reportes',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Presupuestos',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Configuración anual',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Configuración variable',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reportes generales',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Reportes detallados',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Estado de Resultados',
    icon: 'mdi mdi-widgets',
    class: 'has-arrow',
    extralink: false,
    submenu: [
      {
        path: '',
        title: 'Estado de perdidas y ganancias',
        icon: 'mdi mdi-equal',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Balance General',
        icon: 'mdi mdi-message-bulleted',
        class: '',
        extralink: false,
        submenu: [],
      },
      {
        path: '',
        title: 'Flujo de efectivo',
        icon: 'mdi mdi-view-carousel',
        class: '',
        extralink: false,
        submenu: [],
      },
    ],
  },
];
 */